version: "3.7"
services:
  kang:
    container_name: kang
    build:
      context: .
      dockerfile: Dockerfile-alpine
    stdin_open: true # docker run -i
    tty: true
    networks:
      - tcp_puzzler
    depends_on:
      - kodos

  kodos:
    container_name: kodos
    build:
      context: .
      dockerfile: Dockerfile-alpine
    stdin_open: true # docker run -i
    tty: true
    ports:
      - "8080"
    networks:
      - tcp_puzzler

networks:
  tcp_puzzler: {}
